import {
  Badge,
  CodeBlock,
  Columns,
  definePage,
  KeyValue,
  PageHeader,
  Resource,
  Section,
  Table,
  Tabs,
} from "@northgraindata/dsui-adapter-sdk";
import { type ArtifactName, artifactNames } from "../artifacts.js";
import { DependencyGraph } from "../components/dependency-graph.js";
import {
  artifactDetail,
  artifacts,
  models,
  runGraph,
} from "../resources/artifacts.js";
import { sources, tests } from "../resources/catalog.js";
import {
  catalogRelations,
  freshnessRows,
  graphSummaryRows,
  manifestOverview,
  osiOverview,
  runResultRows,
  runResultsOverview,
  semanticMetrics,
  semanticModels,
  semanticOverview,
  semanticSavedQueries,
} from "../resources/explorers.js";

function isArtifactName(value: string): value is ArtifactName {
  return artifactNames.includes(value as ArtifactName);
}

function rawArtifact(source: ReturnType<typeof artifactDetail>) {
  return Resource({
    source,
    content: CodeBlock({
      label: "JSON",
      value: { field: "content" },
      language: "text",
    }),
  });
}

function manifestExplorer(source: ReturnType<typeof artifactDetail>) {
  return Tabs({
    variant: "detail",
    items: [
      {
        label: "Overview",
        content: Columns({
          columns: [
            {
              weight: 1,
              content: Section({
                title: "Manifest",
                description: "Project and generation metadata.",
                content: Resource({
                  source: manifestOverview(),
                  content: KeyValue({
                    title: "Details",
                    source: manifestOverview(),
                  }),
                }),
              }),
            },
            {
              weight: 2,
              content: Section({
                title: "Raw artifact",
                description: "The exact manifest generated by dbt.",
                content: rawArtifact(source),
              }),
            },
          ],
        }),
      },
      {
        label: "Models",
        content: Table({
          source: models(),
          columns: [
            { id: "name", label: "Model" },
            { id: "package", label: "Package" },
            { id: "schema", label: "Schema" },
            { id: "materialized", label: "Materialized" },
            { id: "dependsOn", label: "Upstream" },
          ],
          searchable: true,
          rowLink: {
            path: "/models/:modelId",
            params: { modelId: "uniqueId" },
          },
        }),
      },
      {
        label: "Lineage",
        content: DependencyGraph({
          source: runGraph({ runId: "local-latest" }),
          idField: "graphId",
          dependsOnField: "upstreamGraphIds",
          labelField: "name",
          detailField: "detail",
          stateField: "state",
        }),
      },
      {
        label: "Sources & tests",
        content: Columns({
          columns: [
            {
              content: Section({
                title: "Sources",
                content: Table({
                  source: sources(),
                  columns: [
                    { id: "sourceName", label: "Source" },
                    { id: "name", label: "Table" },
                    { id: "status", label: "Freshness" },
                  ],
                  searchable: true,
                }),
              }),
            },
            {
              content: Section({
                title: "Tests",
                content: Table({
                  source: tests(),
                  columns: [
                    { id: "name", label: "Test" },
                    { id: "attachedTo", label: "Attached to" },
                    { id: "status", label: "Status" },
                  ],
                  searchable: true,
                }),
              }),
            },
          ],
        }),
      },
      { label: "Raw JSON", content: rawArtifact(source) },
    ],
  });
}

function semanticExplorer(source: ReturnType<typeof artifactDetail>) {
  return Tabs({
    variant: "detail",
    items: [
      {
        label: "Overview",
        content: KeyValue({
          title: "Semantic manifest",
          source: semanticOverview(),
        }),
      },
      {
        label: "Semantic models",
        content: Table({
          source: semanticModels(),
          columns: [
            { id: "name", label: "Model" },
            { id: "relation", label: "Relation" },
            { id: "entities", label: "Entities" },
            { id: "measures", label: "Measures" },
            { id: "dimensions", label: "Dimensions" },
          ],
          searchable: true,
        }),
      },
      {
        label: "Metrics",
        content: Table({
          source: semanticMetrics(),
          columns: [
            { id: "name", label: "Metric" },
            { id: "type", label: "Type" },
            { id: "measure", label: "Measure" },
            { id: "description", label: "Description" },
          ],
          searchable: true,
        }),
      },
      {
        label: "Saved queries",
        content: Table({
          source: semanticSavedQueries(),
          columns: [
            { id: "name", label: "Query" },
            { id: "label", label: "Label" },
            { id: "metrics", label: "Metrics" },
            { id: "description", label: "Description" },
          ],
          searchable: true,
        }),
      },
      { label: "Raw JSON", content: rawArtifact(source) },
    ],
  });
}

function catalogExplorer(source: ReturnType<typeof artifactDetail>) {
  return Tabs({
    variant: "detail",
    items: [
      {
        label: "Relations",
        content: Table({
          source: catalogRelations(),
          columns: [
            { id: "name", label: "Relation" },
            { id: "type", label: "Type" },
            { id: "database", label: "Database" },
            { id: "schema", label: "Schema" },
            { id: "columns", label: "Columns" },
          ],
          searchable: true,
        }),
      },
      {
        label: "Raw JSON",
        content: rawArtifact(source),
      },
    ],
  });
}

function runResultsExplorer(source: ReturnType<typeof artifactDetail>) {
  return Tabs({
    variant: "detail",
    items: [
      {
        label: "Summary",
        content: KeyValue({
          title: "Run results",
          source: runResultsOverview(),
        }),
      },
      {
        label: "Results",
        content: Table({
          source: runResultRows(),
          columns: [
            { id: "uniqueId", label: "Node" },
            {
              id: "status",
              label: "Status",
              renderCell: Badge({ label: { field: "status" }, dot: true }),
            },
            { id: "duration", label: "Duration" },
            { id: "failures", label: "Failures" },
            { id: "message", label: "Message" },
          ],
          searchable: true,
        }),
      },
      { label: "Raw JSON", content: rawArtifact(source) },
    ],
  });
}

function explorerFor(
  artifactName: ArtifactName,
  source: ReturnType<typeof artifactDetail>,
) {
  if (artifactName === "manifest.json") return manifestExplorer(source);
  if (artifactName === "semantic_manifest.json")
    return semanticExplorer(source);
  if (artifactName === "catalog.json") return catalogExplorer(source);
  if (artifactName === "run_results.json") return runResultsExplorer(source);
  if (artifactName === "freshness.json" || artifactName === "sources.json")
    return Tabs({
      variant: "detail",
      items: [
        {
          label: "Freshness",
          content: Table({
            source: freshnessRows(),
            columns: [
              { id: "uniqueId", label: "Source" },
              { id: "status", label: "Status" },
              { id: "maxLoadedAt", label: "Last loaded" },
              { id: "snapshottedAt", label: "Checked" },
              { id: "error", label: "Error" },
            ],
            searchable: true,
          }),
        },
        { label: "Raw JSON", content: rawArtifact(source) },
      ],
    });
  if (artifactName === "graph_summary.json")
    return Tabs({
      variant: "detail",
      items: [
        {
          label: "Graph summary",
          content: Table({
            source: graphSummaryRows(),
            columns: [
              { id: "name", label: "Node" },
              { id: "type", label: "Type" },
              { id: "successors", label: "Downstream nodes" },
            ],
            searchable: true,
          }),
        },
        { label: "Raw JSON", content: rawArtifact(source) },
      ],
    });
  if (artifactName === "osi_document.json")
    return Tabs({
      variant: "detail",
      items: [
        {
          label: "Overview",
          content: KeyValue({
            title: "Apache Ossie document",
            source: osiOverview(),
          }),
        },
        { label: "Raw JSON", content: rawArtifact(source) },
      ],
    });
  return rawArtifact(source);
}

export const artifactsPage = definePage({
  path: "/artifacts",
  render: () => [
    PageHeader({
      title: "Artifacts",
      description: "Generated dbt artifacts in the local target directory.",
    }),
    Table({
      source: artifacts(),
      columns: [
        { id: "name", label: "Artifact" },
        { id: "present", label: "Available" },
        { id: "schemaVersion", label: "Schema version" },
        { id: "warning", label: "Warning" },
      ],
      rowLink: {
        path: "/artifacts/:artifactName",
        params: { artifactName: "name" },
      },
    }),
  ],
});

export const artifactDetailPage = definePage({
  path: "/artifacts/:artifactName",
  render: ({ params }) => {
    const artifactName = isArtifactName(params.artifactName)
      ? params.artifactName
      : artifactNames[0];
    const source = artifactDetail({ artifactName });
    return [
      PageHeader({
        title: params.artifactName,
        description: "Explore dbt metadata, results, lineage, and raw output.",
      }),
      Section({
        title: "Artifact explorer",
        content: explorerFor(artifactName, source),
      }),
    ];
  },
});
