import {
  CodeBlock,
  Columns,
  definePage,
  KeyValue,
  PageHeader,
  Resource,
  Section,
  Table,
} from "@northgraindata/dsui-adapter-sdk";
import { type ArtifactName, artifactNames } from "../artifacts.js";
import { artifactDetail, artifacts } from "../resources/artifacts.js";

function isArtifactName(value: string): value is ArtifactName {
  return artifactNames.includes(value as ArtifactName);
}

export const artifactsPage = definePage({
  path: "/artifacts",
  render: () => [
    PageHeader({
      title: "Artifacts",
      description: "Generated dbt artifacts in the local target directory.",
    }),
    Table({
      source: artifacts(),
      columns: [
        { id: "name", label: "Artifact" },
        { id: "present", label: "Available" },
        { id: "schemaVersion", label: "Schema version" },
        { id: "warning", label: "Warning" },
      ],
      rowLink: {
        path: "/artifacts/:artifactName",
        params: { artifactName: "name" },
      },
    }),
  ],
});

export const artifactDetailPage = definePage({
  path: "/artifacts/:artifactName",
  render: ({ params }) => {
    const artifactName = isArtifactName(params.artifactName)
      ? params.artifactName
      : artifactNames[0];
    const source = artifactDetail({ artifactName });
    return [
      PageHeader({
        title: params.artifactName,
        description: "Inspect the exact JSON artifact generated by dbt.",
      }),
      Columns({
        columns: [
          {
            weight: 1,
            content: Section({
              title: "Artifact details",
              content: Resource({
                source,
                content: KeyValue({ title: "Metadata", source }),
              }),
            }),
          },
          {
            weight: 2,
            content: Section({
              title: "Contents",
              description: "Read-only JSON generated by the last dbt command.",
              content: Resource({
                source,
                content: CodeBlock({
                  label: "JSON",
                  value: { field: "content" },
                  language: "text",
                }),
              }),
            }),
          },
        ],
      }),
    ];
  },
});
