import {
  CodeBlock,
  Columns,
  definePage,
  KeyValue,
  PageHeader,
  Resource,
  Section,
  Table,
} from "@northgraindata/dsui-adapter-sdk";
import { DependencyGraph } from "../components/dependency-graph.js";
import { runGraph } from "../resources/artifacts.js";
import { runArtifacts, runDetail, runLogs } from "../resources/run-detail.js";
import { dbtRunStore } from "../stores/runs.js";

export const runDetailPage = definePage({
  path: "/runs/:runId",
  stores: [dbtRunStore],
  render: ({ params, stores }) => {
    const input = { runId: params.runId };
    const archived = stores
      .use(dbtRunStore)
      .runs.find((run) => run.id === params.runId);
    const summary = archived
      ? {
          id: archived.id,
          status: archived.status,
          job: archived.job,
          cause: archived.cause,
          startedAt: archived.startedAt,
          duration: `${(archived.durationMs / 1000).toFixed(2)}s`,
          exitCode: archived.exitCode,
        }
      : undefined;
    return [
      PageHeader({
        title: `Run ${params.runId}`,
        description: "dbt Cloud run details and generated artifacts.",
      }),
      Columns({
        columns: [
          {
            weight: 2,
            content: [
              Section({
                title: "Summary",
                description: "Execution status and timing for this dbt run.",
                content: summary
                  ? KeyValue({ title: "Run", data: summary })
                  : KeyValue({ title: "Run", source: runDetail(input) }),
              }),
              Section({
                title: "Logs",
                description: "Process output and dbt diagnostic logs.",
                content: archived
                  ? CodeBlock({
                      label: "dbt output",
                      value: { field: "content" },
                      language: "text",
                      data: {
                        content: [archived.stdout, archived.stderr]
                          .filter(Boolean)
                          .join("\n\n"),
                      },
                    })
                  : Resource({
                      source: runLogs(input),
                      content: CodeBlock({
                        label: "dbt output",
                        value: { field: "content" },
                        language: "text",
                      }),
                    }),
              }),
              Section({
                title: "Lineage",
                description:
                  "Model dependencies and execution state for this run.",
                content: DependencyGraph({
                  source: runGraph(input),
                  idField: "graphId",
                  dependsOnField: "upstreamGraphIds",
                  labelField: "name",
                  detailField: "detail",
                  stateField: "state",
                }),
              }),
            ],
          },
          {
            content: Section({
              title: "Artifacts",
              description: "Files generated by this run.",
              content: archived
                ? Table({
                    data: archived.artifacts.map((artifact) => ({
                      name: artifact.name,
                      content_type: artifact.contentType,
                      size: artifact.size,
                    })),
                    columns: [
                      { id: "name", label: "Artifact" },
                      { id: "content_type", label: "Type" },
                      { id: "size", label: "Size" },
                    ],
                    rowLink: {
                      path: "/artifacts/:artifactName",
                      params: { artifactName: "name" },
                    },
                  })
                : Table({
                    source: runArtifacts(input),
                    columns: [
                      { id: "name", label: "Artifact" },
                      { id: "content_type", label: "Type" },
                      { id: "size", label: "Size" },
                    ],
                  }),
            }),
          },
        ],
      }),
    ];
  },
});
