/**
 * DSUI adapter SDK: Resource = data, Store = state, Action = behavior,
 * Page = composition, Context = environment, Adapter = application boundary.
 */
import { z } from "zod";
import { ADAPTER_SDK_VERSION } from "./adapter/index";

export {
  type ActionBinding,
  type ActionDefinition,
  type ActionExecutionStatus,
  type ActionExecutionWithSignals,
  type ActionFailure,
  type ActionReference,
  type ActionResult,
  type ActionRuntimeContext,
  type ActionSuccess,
  type ActionTarget,
  type AnyActionDefinition,
  defineAction,
  type InputAction,
  type InputlessAction,
} from "./action/index";
export {
  ADAPTER_SDK_VERSION,
  type AdapterDefinition,
  type AdapterHealthCheck,
  type AdapterHealthReport,
  type AdapterInfo,
  type ConnectionMethodDefinition,
  type ConnectionRequestConcurrency,
  type DefineAdapterOptions,
  defineAdapter,
  healthReport,
  reachabilityCheck,
  type SignalWeight,
  scoreChecks,
  statusFor,
} from "./adapter/index";
export {
  Badge,
  type BadgeNode,
  type BadgeProps,
  type BadgeTone,
  Button,
  type ButtonNode,
  type ButtonProps,
  Card,
  type CardBadgeTone,
  type CardNode,
  type CardProps,
  type CardValue,
  type CardVariant,
  Chart,
  type ChartKind,
  type ChartNode,
  type ChartPoint,
  type ChartProps,
  type ChartScale,
  type ChartWindow,
  CodeBlock,
  type CodeBlockNode,
  type CodeBlockProps,
  CodeEditor,
  type CodeEditorNode,
  type CodeEditorProps,
  Collection,
  type CollectionNode,
  type CollectionProps,
  Columns,
  type ColumnsColumn,
  type ColumnsNode,
  type ColumnsProps,
  type ComponentReferenceNode,
  type ComponentReferenceProps,
  defineComponent,
  type FieldReference,
  Flex,
  type FlexAlign,
  type FlexDirection,
  type FlexJustify,
  type FlexNode,
  type FlexProps,
  Form,
  type FormNode,
  type FormProps,
  Gauge,
  type GaugeProps,
  type GaugeScale,
  type GaugeTone,
  Grid,
  type GridNode,
  type GridProps,
  Icon,
  type IconNode,
  type IconProps,
  KeyValue,
  type KeyValueNode,
  type KeyValueProps,
  type LayoutGap,
  Link,
  type LinkNode,
  type LinkProps,
  Meter,
  type MeterData,
  type MeterNode,
  type MeterProps,
  type MeterSegment,
  Notebook,
  type NotebookBlock,
  NotebookCatalog,
  type NotebookCatalogItem,
  type NotebookCatalogNode,
  type NotebookCatalogProps,
  type NotebookNode,
  type NotebookProps,
  type PageDocument,
  PageHeader,
  type PageHeaderAction,
  type PageHeaderBadge,
  type PageHeaderNode,
  type PageHeaderProps,
  type PageMeterData,
  type PageMeterSegment,
  type PageNode,
  type PageSectionLink,
  type PageTableRowAction,
  type PageTableRowLink,
  QueryEditor,
  type QueryEditorExplorerProps,
  type QueryEditorNode,
  type QueryEditorProps,
  type QueryExplorerDocument,
  Resource,
  type ResourceNode,
  type ResourceProps,
  ResourceTree,
  type ResourceTreeBranchDocument,
  type ResourceTreeBranchProps,
  type ResourceTreeNode,
  type ResourceTreeProps,
  Section,
  type SectionLink,
  type SectionNode,
  type SectionProps,
  Select,
  type SelectNode,
  type SelectOption,
  type SelectProps,
  SplitPane,
  type SplitPaneNode,
  type SplitPaneProps,
  Stack,
  type StackNode,
  type StackProps,
  serializeNode,
  serializeNodes,
  Table,
  type TableColumn,
  type TableFilter,
  type TableNode,
  type TableProps,
  type TableRowAction,
  type TableRowLink,
  type TableRowMenuAction,
  Tabs,
  type TabsItem,
  type TabsNode,
  type TabsProps,
  TextInput,
  type TextInputNode,
  type TextInputProps,
  toneForValue,
  UnserializablePageError,
  Value,
  type ValueFormat,
  type ValueNode,
  type ValueProps,
} from "./components/index";
export type { ComponentClient, ComponentProps } from "./components/runtime";
export { componentProps } from "./components/runtime";
export {
  type AnyJobDefinition,
  type DefineJobOptions,
  defineJob,
  InvalidJobDefinitionError,
  type JobConcurrency,
  type JobDefinition,
  type JobRetry,
  type JobRunInput,
  type SignalEmission,
} from "./job";
export {
  type AnyPageDefinition,
  definePage,
  type ExtractRouteParams,
  matchRoute,
  type PageRenderContext,
  type StoreAccessor,
} from "./page/index";
export {
  manual,
  type PollInterval,
  poll,
  type RefreshStrategy,
} from "./refresh/index";
export {
  type AnyResourceDefinition,
  type DataSource,
  defineResource,
  type InputlessResource,
  type InputResource,
  type ResourceBinding,
  type ResourceDefinition,
  type ResourceReference,
  type ResourceRuntimeContext,
} from "./resource/index";
export {
  type ActionExecutionOptions,
  type AdapterInstance,
  createAdapterInstance,
  type JobExecutionOptions,
  type PageScope,
  type ResourceFailure,
  type ResourceResult,
  type ResourceStatus,
  type ResourceSuccess,
  resourceKey,
  stableStringify,
} from "./runtime/index";
export {
  InvalidDefinitionError,
  SdkError,
  UnknownPageError,
} from "./shared/errors";
export {
  type AnySignalDefinition,
  type DefineSignalOptions,
  defineSignal,
  type SignalDefinition,
  type SignalType,
} from "./signal";
export {
  type AnyStoreDefinition,
  type CreateStoreInstanceOptions,
  createStoreInstance,
  defineStore,
  MemoryStorePersistenceProvider,
  type StoreDefinition,
  type StoreHelpers,
  type StoreInstance,
  type StorePersistence,
  type StorePersistenceProvider,
  type StorePersistenceRequest,
  type StoreScope,
  type StoreStatus,
} from "./store/index";
export { z };

export { CodeExplorer } from "./components/primitives/code-explorer";
export type {
  CodeExplorerProps,
  CodeExplorerFile,
  CodeExplorerContent,
} from "./components/primitives/code-explorer";
